### ISSUE TITLE
@switch feature not working with 6.4.0 cq-component-maven-plugin

### ISSUE THREAD

**Issue by sagarkmr09** [icfnext/cq-component-maven-plugin#85]
Hi,

I am using AEM 6.5 and using cq-component-maven-plugin for dialog creation.

@switch anotation is not working as expected when used with 6.5 uber jar and 6.4.0 cq-component-maven-plugin.

The offText and onText values doesn't display in the dialog.

Thanks

**Comment by sagarkmr09** [comment]
Can you please let us know if we are missing anything here?

Thanks

**Comment by nicklapaglia** [comment]
The display of the offText and onText properties for the switch widget is not supported out of the box in Coral UI 3. One option to to remedy would be to set the useCoral3Dialogs POM configuration to false.
