### ISSUE TITLE
Tab node gets created when creating dialog using 6.4.0 cq-component-maven-plugin

### ISSUE THREAD

**Issue by sagarkmr09** [icfnext/cq-component-maven-plugin#86]
Hi,

We are using AEM 6.5, uber jar version 6.5.0 and using cq-component-maven-plugin 6.4.0 for dialog creation.
When dialog created by extend feature from another class, a tab node of gets created of 
sling:resourceType: "granite/ui/components/coral/foundation/tabs"

in addition to sling:resourceType: granite/ui/components/foundation/section created by @tab annotation.

Can you please let us know if we are missing anything here?

Thanks

When used the same in AEM 6.3, uber jar 6.3 and with cq-component-maven-plugin 5.0.0 with @tab annotation, node with gets created with below resourceType.
sling:resourceType: granite/ui/components/foundation/section

**Comment by nicklapaglia** [comment]
I am unable to reproduce the above specified issue with the details provided. Please provide additional specific details on what needs to be done to reproduce issue.
